### ISSUE TITLE
Did not find this attribute

### ISSUE THREAD

**Issue by leon456** [blackfizz/EazeGraph#41]
No resource identifier found for attribute 'egIndicatorLineColor' in package

when I add this attribute in layout xml
 I got above error,how can I solve this issue,thanks

**Comment by leon456** [comment]
My  reference as below

compile 'com.github.blackfizz:eazegraph:1.2.5l@aar'
compile 'com.nineoldandroids:library:2.4.0'

**Comment by blackfizz** [comment]
You are using the Lightweight version of my library, which doesn't support any user input or user feedback, such as an indicator. You need to use the normal version:

`compile 'com.github.blackfizz:eazegraph:1.2.0@aar'`

This one supports user input and user feedback through an indicator.
